#!/bin/bash

FILE=$1
OUT=$(basename "$FILE").out

set -e

lua format.lua $1 > "$OUT"

diff <(luac -l -p "$FILE" | awk '{ if ($1 ~ /^[0-9]+$/) { print $1, $3, $4, $5, $6, $7, $8 } }' | grep --invert-match CLOSURE) <(luac -l -p "$OUT" | awk '{ if ($1 ~ /^[0-9]+$/) { print $1, $3, $4, $5, $6, $7, $8 } }' | grep --invert-match CLOSURE)
